export default function PokemonApp() {
    return (
        <>
            <div> 
                <div>
                    <h>Name</h> 
                    <div>
                        <div>
                            <image></image>
                            <div>
                                <types></types>
                            </div>
                        </div>
                        <div>
                            <stats></stats>
                        </div>
                        <div>
                            <abilities></abilities>
                        </div>
                    </div> 
                </div>
                <div>
                    <div>
                        <typefilters></typefilters>
                    </div>  
                    <div>
                        <pokemons>
                            <p>No. iii:</p>
                            <p>Name</p>
                            <div>
                                <types></types>
                            </div>
                        </pokemons>
                    </div>
                </div>
            </div>
        </>
    )
}